specVersion: 0.2.0
name: parascan-subql-starter
version: 1.0.0
description: subql starter for parascan
repository: "https://github.com/parascan/parascan-subql-starter"
schema:
  file: ./schema.graphql

network:
  endpoint: wss://rpc.efinity.io
  genesisHash: "0x335369975fced3fc22e23498da306a712f4fd964c957364d53c49cea9db8bc2f"

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
